In [1]:
import tensorflow as tf 
sess = tf.InteractiveSession()

In [12]:
x = tf.constant([[2, 5, 3, -5], 
                 [0, 3,-2,  5], 
                 [4, 3, 5,  3], 
                 [6, 1, 4,  0]]) 
listx = tf.constant([1,2,3,4,5,6,7,8,8])
listy = tf.constant([4,5,8,9])
boolx = tf.constant([[True,False], [False,True]])

In [3]:
tf.argmin(x, 1).eval() # Position of the maximum value of columns

array([3, 2, 1, 3], dtype=int64)

In [4]:
tf.argmax(x, 1).eval() # Position of the minimum value of rows

array([1, 3, 2, 0], dtype=int64)

In [9]:
tf.setdiff1d(listx, listy)[0].eval() # List differences

array([1, 2, 3, 6, 7])

In [10]:
tf.where(boolx).eval() # Show true values

array([[0, 0],
       [1, 1]], dtype=int64)

In [14]:
tf.unique(listx)[0].eval() # Unique values in list

array([1, 2, 3, 4, 5, 6, 7, 8])