In [2]:
import tensorflow as tf

In [3]:
sess=tf.InteractiveSession()

In [5]:
x = tf.constant([[2, 5, 3, -5], 
                 [0, 3,-2,  5], 
                 [4, 3, 5,  3], 
                 [6, 1, 4,  0]]) 
                 


In [6]:
y = tf.constant([[4, -7, 4, -3, 4], 
                 [6, 4,-7,  4, 7], 
                 [2, 3, 2,  1, 4], 
                 [1, 5, 5,  5, 2]])



In [7]:
floatx = tf.constant([[2., 5., 3., -5.], 
                      [0., 3.,-2.,  5.], 
                      [4., 3., 5.,  3.], 
                      [6., 1., 4.,  0.]]) 
                 


In [8]:
tf.transpose(x).eval() # Transpose matrix


array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]])

In [9]:
tf.matmul(x, y).eval() # Matrix multiplication


array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]])

In [10]:
tf.matrix_determinant(floatx).eval() # Matrix determinant


818.0

In [11]:
tf.matrix_inverse(floatx).eval() # Matrix inverse


array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.2811736 , -0.1809291 ],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]],
      dtype=float32)

In [12]:
tf.matrix_solve(floatx, [[1],[1],[1],[1]]).eval() # Solve Matrix system

array([[ 0.202934  ],
       [ 0.21271393],
       [-0.10757945],
       [ 0.02933985]], dtype=float32)