In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
x = tf.constant([[2, 5, 3, -5], 
                 [0, 3,-2,  5], 
                 [4, 3, 5,  3], 
                 [6, 1, 4,  0]])

In [3]:
tf.shape(x).eval() # Shape of the tensor

array([4, 4])

In [4]:
tf.size(x).eval() # size of the tensor

16

In [5]:
tf.rank(x).eval() # rank of the tensor

2

In [6]:
tf.reshape(x, [8, 2]).eval() # converting to a 10x2 matrix

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [-2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]])

In [7]:
tf.squeeze(x).eval() #  squeezing

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]])

In [8]:
tf.expand_dims(x,1).eval() #Expanding dims

array([[[ 2,  5,  3, -5]],

       [[ 0,  3, -2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]])