In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[1,  2, 3], 
                 [3,  2, 1], 
                 [-1,-2,-3]])
boolean_tensor = tf.constant([[True,  False, True], 
                 [False, False, True], 
                 [True, False, False]])   

In [5]:
tf.reduce_prod(x, reduction_indices=1).eval() # reduce prod

array([ 6,  6, -6])

In [6]:
tf.reduce_min(x, reduction_indices=1).eval() # reduce min

array([ 1,  1, -3])

In [7]:
tf.reduce_max(x, reduction_indices=1).eval() # reduce max

array([ 3,  3, -1])

In [8]:
tf.reduce_mean(x, reduction_indices=1).eval() # reduce mean

array([ 2,  2, -2])

In [9]:
tf.reduce_all(boolean_tensor, reduction_indices=1).eval() # reduce all 

array([False, False, False])

In [10]:
tf.reduce_any(boolean_tensor, reduction_indices=1).eval() # reduce any

array([ True,  True,  True])