In [7]:
import tensorflow as tf
import numpy as np
sess=tf.InteractiveSession()

In [3]:
t_matrix=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t_array=tf.constant([1,2,3,4,9,8,6,5])
t_array2=tf.constant([2,3,4,5,6,7,8,9])

In [4]:
tf.slice(t_matrix,[1,1],[2,2]).eval()

array([[5, 6],
       [8, 9]])

In [14]:
tf.split(t_array,2,0)

[<tf.Tensor 'split_3:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split_3:1' shape=(4,) dtype=int32>]

In [17]:
tf.tile([1,2],[3]).eval()

array([1, 2, 1, 2, 1, 2])

In [18]:
tf.pad(t_matrix,[[0,1],[2,1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]])

In [20]:
tf.concat([t_array,t_array2],0).eval()

array([1, 2, 3, 4, 9, 8, 6, 5, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
tf.stack([t_array,t_array2]).eval()

array([[1, 2, 3, 4, 9, 8, 6, 5],
       [2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
sess.run(tf.unstack(t_matrix))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [25]:
tf.reverse(t_matrix,[False,True]).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [8]:
a=np.reshape(range(24),(4,2,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [9]:
b= tf.split(a,2,1)
b

[<tf.Tensor 'split_1:0' shape=(4, 1, 3) dtype=int32>,
 <tf.Tensor 'split_1:1' shape=(4, 1, 3) dtype=int32>]

In [10]:
sess.run(b)

[array([[[ 0,  1,  2]],
 
        [[ 6,  7,  8]],
 
        [[12, 13, 14]],
 
        [[18, 19, 20]]]), array([[[ 3,  4,  5]],
 
        [[ 9, 10, 11]],
 
        [[15, 16, 17]],
 
        [[21, 22, 23]]])]

In [11]:
c= tf.split(a,2,0)

In [12]:
c

[<tf.Tensor 'split_2:0' shape=(2, 2, 3) dtype=int32>,
 <tf.Tensor 'split_2:1' shape=(2, 2, 3) dtype=int32>]

In [13]:
sess.run(c)

[array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]), array([[[12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23]]])]

In [15]:
d= tf.split(a,3,2)
d

[<tf.Tensor 'split_4:0' shape=(4, 2, 1) dtype=int32>,
 <tf.Tensor 'split_4:1' shape=(4, 2, 1) dtype=int32>,
 <tf.Tensor 'split_4:2' shape=(4, 2, 1) dtype=int32>]

In [16]:
sess.run(d)

[array([[[ 0],
         [ 3]],
 
        [[ 6],
         [ 9]],
 
        [[12],
         [15]],
 
        [[18],
         [21]]]), array([[[ 1],
         [ 4]],
 
        [[ 7],
         [10]],
 
        [[13],
         [16]],
 
        [[19],
         [22]]]), array([[[ 2],
         [ 5]],
 
        [[ 8],
         [11]],
 
        [[14],
         [17]],
 
        [[20],
         [23]]])]