In [1]:
import tensorflow as tf
import numpy as np
sess=tf.Session()

In [2]:
tens1=tf.constant([[[1,2],[2,3,]],[[3,4],[5,6]]])
print(sess.run(tens1)[1,1,0])

5


In [3]:
x=tf.constant(np.random.rand(32).astype(np.float32))
y=tf.constant([1,2,3])
print(sess.run(x))
print(sess.run(y))

[0.72277784 0.5555583  0.9727003  0.42747948 0.8584127  0.04486032
 0.53186893 0.00307672 0.3903728  0.6949591  0.9316994  0.49219966
 0.53806627 0.36071035 0.6936045  0.29451767 0.29325756 0.48242182
 0.8227579  0.08943313 0.5462339  0.6578592  0.10467882 0.5918882
 0.974299   0.9077737  0.09806631 0.70363283 0.26283985 0.00631195
 0.18808503 0.62087345]
[1 2 3]


In [4]:
x_data=np.array([[1.,2.,3.],[3.,2.,6.]])
x=tf.convert_to_tensor(x_data,dtype=tf.float32)
print(sess.run(x))

[[1. 2. 3.]
 [3. 2. 6.]]


In [8]:
b=tf.Variable(tf.zeros([1000]))
b
##print(sess.run(b))

<tf.Variable 'Variable_3:0' shape=(1000,) dtype=float32_ref>