In [1]:
#Segmentation Examples
import tensorflow as tf
sess = tf.InteractiveSession()

In [2]:
seg_ids = tf.constant([0,1,1,2,2]); # Group indexes : 0|1,2|3,4

In [4]:
tens1 = tf.constant([[2, 5, 3, -5],  
                    [0, 3,-2,  5], 
                    [4, 3, 5,  3], 
                    [6, 1, 4,  0],
                    [6, 1, 4,  0]])  # A sample constant matrix

In [5]:
tf.segment_sum(tens1, seg_ids).eval()   # Sum segmentation

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]])

In [6]:
tf.segment_prod(tens1, seg_ids).eval() # Product segmantation

array([[  2,   5,   3,  -5],
       [  0,   9, -10,  15],
       [ 36,   1,  16,   0]])

In [7]:
tf.segment_min(tens1, seg_ids).eval() # minimun value goes to group

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]])

In [8]:
tf.segment_max(tens1, seg_ids).eval() # maximum value goes to group

array([[ 2,  5,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]])

In [9]:
tf.segment_mean(tens1, seg_ids).eval() # mean value goes to group

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]])